---
- name: Install iproute2mac
  community.general.homebrew:
    name: iproute2mac
    state: latest
  become_user: '{{ ansible_user }}'

- name: Create packet filter script
  ansible.builtin.file:
    state: directory
    dest: '{{ macos_pf_script_dir }}'

- name: Create packet filter script
  ansible.builtin.template:
    src: firewall.sh.j2
    dest: '{{ macos_pf_script_path }}'
    mode: '0755'
  register: script

- name: Create packet filter config
  ansible.builtin.template:
    src: pf.config.j2
    dest: '{{ macos_pf_config_path }}'
  register: config

- name: Create packet filter anchor
  ansible.builtin.template:
    src: pf.rules.j2
    dest: '{{ macos_pf_anchor_path }}'
    validate: /sbin/pfctl -nf %s
  register: anchor

- name: Reload packet filter config
  ansible.builtin.command: '{{ macos_pf_script_path }}'
  when: >
    ( script is changed or
      config is changed or
      anchor is changed )

- name: Create packet filter config
  ansible.builtin.template:
    src: pfctl.plist.j2
    dest: '{{ macos_pf_plist }}'
  register: plist

- name: 'Start {{ macos_pf_anchor }}.pfctl'
  community.general.launchd:
    name: '{{ macos_pf_anchor }}.pfctl'
    state: started
  when: plist is changed

- name: Enable/Disable default MacOS firewall
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.alf
    key: globalstate
    type: int
    value: "{{ 1 if macos_pf_default_firewal else 0 }}"
    state: present
  register: firewall

- name: Message about default MacOS firewall
  ansible.builtin.debug:
    msg:
    - "WARNING! Default MacOS firewall {{ 'enabled' if macos_pf_default_firewal else 'disabled' }}. Need reboot system to apply changes!{{ ' Be careful you may lose remote access to MacOS!' if macos_pf_default_firewal }}"
  when: firewall is changed

