---
- name: Create packet filter anchor
  copy:
    content: '{{ macos_pf_rules }}'
    dest: '{{ macos_pf_anchor_path }}'
  register: anchor

- name: Change packet filter config
  lineinfile:
    path: '{{ macos_pf_config_path }}'
    line: '{{ item }}'
    backup: yes
  with_items:
    - 'anchor "{{ macos_pf_anchor }}"'
    - 'load anchor "{{ macos_pf_anchor }}" from "{{ macos_pf_anchor_path }}"'
  register: config

- name: Verify packet filter config
  command: pfctl -nf '{{ macos_pf_config_path }}'
  changed_when: no

- name: Reload packet filter config
  command: pfctl -f '{{ macos_pf_config_path }}'
  when: anchor is changed or config is changed

- name: Verify packet filter is enabled
  shell: >
    pfctl -s info 2>/dev/null | egrep -i '^status: enabled'
  ignore_errors: yes
  changed_when: no
  register: pf_enabled

- name: Enable packet filter
  command: pfctl -e
  when: pf_enabled is failed

- name: Enable packet filter permanently
  lineinfile:
    path: '{{ macos_pf_plist }}'
    line: "\t\t<string>-e</string>"
    insertafter: '<string>pfctl</string>'
  ignore_errors: yes
  register: enable_pf_permanently
  when: enable_pf_permanently_sip

- name: Fail when packet filter couldn't be enabled permanently
  fail:
    msg: >
      You must disable System Integrity Protection (SIP) during this run!
      Otherwise the Packet Filter can't be enabled permanently across reboots.
  when: enable_pf_permanently is failed and not macos_pf_ignore_sip

- name: Ensure directory is exist
  file:
    path: '{{ macos_user_launch_agents }}'
    state: directory
    owner: '{{ ansible_ssh_user }}'
  when: enable_pf_permanently_user is defined

- name: Enable packet filter permanently on user level
  copy:
    src: files/com.user.pfloginscript.plist
    dest: '{{ macos_user_launch_agents }}'
    owner: '{{ ansible_ssh_user }}'
  register: enable_pf_permanently
  when: enable_pf_permanently_user is defined

- name: Enabled packet filter on user (auto)login
  block:
    - command: launchctl load -w {{ macos_user_pf_plist }}
    
    - debug:
        msg: >
          You must add user to sudoers without password! Otherwise the Packet Filter can't be enabled permanently across reboots.
  when: enable_pf_permanently_user is defined and pf_enabled is failed